version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: enzo
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: nextask_db
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistance des données
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgresql://enzo:supersecretpassword@postgres:5432/nextask_db?schema=public"
      JWT_SECRET: "ton_secret_jwt"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:4000"
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  pgdata: # Déclaration du volume pour éviter la perte des données au redémarrage
