name: Backend CI

# 1. Quand est-ce que ce robot doit se réveiller ?
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# 2. Que doit-il faire ?
jobs:
  test-and-build:
    runs-on: ubuntu-latest # Le système d'exploitation du robot

    steps:
      # Étape A : Le robot télécharge ton code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape B : Le robot installe Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20" # La version standard actuelle
          cache: "npm"

      # Étape C : Installer les dépendances de ton projet
      - name: Install dependencies
        # TODO 1 : Remplace la commande 'echo' par la BONNE commande NPM pour installer les dépendances proprement dans une CI (voir les erreurs de juniors au-dessus).
        run: npm ci

      # Étape D : Générer le client Prisma (Crucial, sinon NestJS ne comprendra pas Prisma)
      - name: Generate Prisma Client
        run: npx prisma generate

      # Étape E : Lancer le linter (Vérifier la syntaxe)
      - name: Run Linter
        # TODO 2 : Remplace par la commande npm qui lance ton linter (regarde dans les scripts de ton package.json)
        run: npm run lint

      # Étape F : Lancer les tests unitaires que tu viens de coder !
      - name: Run Unit Tests
        # TODO 3 : Remplace par la commande npm qui lance les tests unitaires.
        run: npm run test
