name: Backend CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      # Étape A : Le robot télécharge le code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape B : Le robot installe Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: ./backend/package-lock.json

      # Étape C : Installer les dépendances du projet
      - name: Install dependencies
        run: npm ci

      # Étape D : Générer le client Prisma
      - name: Generate Prisma Client
        run: npx prisma generate

      # Étape E : Lancer le linter
      - name: Run Linter
        run: npm run lint

      # Étape F : Lancer les tests unitaires que tu viens de coder !
      - name: Run Unit Tests
        run: npm run test
